name: Publish to npm

on:
  push:
    tags:
      - 'v*' # Trigger workflow on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Updated to v3
        with:
          node-version: '16' # Specify your Node.js version here
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Ensure you have set this secret in your GitHub repo
        run: npm publish --access public
